name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verify GIT_SHA
        run: echo "GIT_SHA=${{ env.SHA }}"

      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t nadjibdeveloper/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true nadjibdeveloper/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-465313

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: europe-west1-b

      - name: Build
        run: |-
          docker build -t nadjibdeveloper/multi-client-k8s-gh:latest -t nadjibdeveloper/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t nadjibdeveloper/multi-server-k8s-gh:latest -t nadjibdeveloper/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t nadjibdeveloper/multi-worker-k8s-gh:latest -t nadjibdeveloper/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push nadjibdeveloper/multi-client-k8s-gh:latest
          docker push nadjibdeveloper/multi-server-k8s-gh:latest
          docker push nadjibdeveloper/multi-worker-k8s-gh:latest

          docker push nadjibdeveloper/multi-client-k8s-gh:${{ env.SHA }}
          docker push nadjibdeveloper/multi-server-k8s-gh:${{ env.SHA }}
          docker push nadjibdeveloper/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=nadjibdeveloper/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=nadjibdeveloper/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=nadjibdeveloper/multi-worker-k8s-gh:${{ env.SHA }}
